use crate::Video;

pub fn setData (vid: &mut Video) {
    vid.setSpriteData(0, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(1, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(2, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(3,
      &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(4, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaa..aaaa..a  ",
      "  aa....aa....  ",
      "  aa..()aa..()  ",
      " aaa..()aa..()a ",
      " aaaa..aaaa..aa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(5, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
       "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaa..aaaa..a  ",
      "  aa....aa....  ",
      "  aa..()aa..()  ",
      " aaa..()aa..()a ",
      " aaaa..aaaa..aa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(6, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(7, &[(' ',0), ('(',4), (')',4), ('a',9), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(8, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(9, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(10, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
       " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(11, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(12, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
       "                ",
       "      aaaa      ",
       "    aaaaaaaa    ",
       "   aaaaaaaaaa   ",
       "  aaa..aaaa..a  ",
       "  aa....aa....  ",
       "  aa..()aa..()  ",
       " aaa..()aa..()a ",
       " aaaa..aaaa..aa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aa aaa  aaa aa ",
       " a   aa  aa   a ",
       "                "]);
    vid.setSpriteData(13, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaa..aaaa..a  ",
      "  aa....aa....  ",
      "  aa..()aa..()  ",
      " aaa..()aa..()a ",
      " aaaa..aaaa..aa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(14, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(15, &[(' ',0), ('(',4), (')',4), ('a',13), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(16, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(17, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(18, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(19, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(20, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
       "                ",
       "      aaaa      ",
       "    aaaaaaaa    ",
       "   aaaaaaaaaa   ",
       "  aaa..aaaa..a  ",
       "  aa....aa....  ",
       "  aa..()aa..()  ",
       " aaa..()aa..()a ",
       " aaaa..aaaa..aa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aa aaa  aaa aa ",
       " a   aa  aa   a ",
       "                "]);
    vid.setSpriteData(21, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaa..aaaa..a  ",
      "  aa....aa....  ",
      "  aa..()aa..()  ",
      " aaa..()aa..()a ",
      " aaaa..aaaa..aa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(22, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(23, &[(' ',0), ('(',4), (')',4), ('a',14), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(24, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(25, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    ()aaaa()    ",
      "   .().aa.().   ",
      "  a....aa....a  ",
      "  a....aa....a  ",
      "  aa..aaaa..aa  ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(26, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(27, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  a..aaaa..aaa  ",
      "  ....aa....aa  ",
      "  ()..aa()..aa  ",
      " a()..aa()..aaa ",
      " aa..aaaa..aaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(28, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
       "                ",
       "      aaaa      ",
       "    aaaaaaaa    ",
       "   aaaaaaaaaa   ",
       "  aaa..aaaa..a  ",
       "  aa....aa....  ",
       "  aa..()aa..()  ",
       " aaa..()aa..()a ",
       " aaaa..aaaa..aa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aaaaaaaaaaaaaa ",
       " aa aaa  aaa aa ",
       " a   aa  aa   a ",
       "                "]);
    vid.setSpriteData(29, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaa..aaaa..a  ",
      "  aa....aa....  ",
      "  aa..()aa..()  ",
      " aaa..()aa..()a ",
      " aaaa..aaaa..aa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    vid.setSpriteData(30, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aa aaa  aaa aa ",
      " a   aa  aa   a ",
      "                ",]);
    vid.setSpriteData(31, &[(' ',0), ('(',4), (')',4), ('a',3), ('.',15)], &[
      "                ",
      "      aaaa      ",
      "    aaaaaaaa    ",
      "   aaaaaaaaaa   ",
      "  aaaaaaaaaaaa  ",
      "  aa..aaaa..aa  ",
      "  a....aa....a  ",
      " aa....aa....aa ",
      " aa.().aa.().aa ",
      " aaa()aaaa()aaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaaaaaaaaaaaa ",
      " aaaa aaaa aaaa ",
      "  aa   aa   aa  ",
      "                ",]);
    // pukman

    vid.setSpriteData(32, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "   ooooooooo    ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      " ooooooooooooo  ",
      " ooooooooooooo  ",
      " ooooooooooooo  ",
      " ooooooooooooo  ",
      " ooooooooooooo  ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      "   ooooooooo    ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(33, &[(' ',0), ('o',11)], &[
      "                ",
      "                ",
      "   oo     oo    ",
      "  ooo     ooo   ",
      "  oooo   oooo   ",
      " ooooo   ooooo  ",
      " ooooo   ooooo  ",
      " oooooo oooooo  ",
      " oooooo oooooo  ",
      " oooooo oooooo  ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      "   ooooooooo    ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(34, &[(' ',0), ('o',11)], &[
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      " oo         oo  ",
      " ooo       ooo  ",
      " oooo     oooo  ",
      " ooooo   ooooo  ",
      " oooooo oooooo  ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      "   ooooooooo    ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(35, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "   ooooooooo    ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      "    oooooooooo  ",
      "       ooooooo  ",
      "          oooo  ",
      "       ooooooo  ",
      "    oooooooooo  ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      "   ooooooooo    ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(36, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "     ooooooo    ",
      "     oooooooo   ",
      "       oooooo   ",
      "        oooooo  ",
      "         ooooo  ",
      "          oooo  ",
      "         ooooo  ",
      "        oooooo  ",
      "       oooooo   ",
      "      ooooooo   ",
      "     ooooooo    ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(37, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "   ooooooooo    ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      " oooooooooo     ",
      " ooooooo        ",
      " oooo           ",
      " ooooooo        ",
      " oooooooooo     ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      "   ooooooooo    ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(38, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "   ooooooo      ",
      "  ooooooo       ",
      "  oooooo        ",
      " oooooo         ",
      " ooooo          ",
      " oooo           ",
      " ooooo          ",
      " oooooo         ",
      "  oooooo        ",
      "  ooooooo       ",
      "   ooooooo      ",
      "     ooooo      ",
      "                ",
      "                ",]);
    vid.setSpriteData(39, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "   ooooooooo    ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      " oooooo oooooo  ",
      " oooooo oooooo  ",
      " oooooo oooooo  ",
      " ooooo   ooooo  ",
      " ooooo   ooooo  ",
      "  oooo   oooo   ",
      "  ooo     ooo   ",
      "   oo     oo    ",
      "                ",
      "                ",
      "                ",]);
    vid.setSpriteData(40, &[(' ',0), ('o',11)], &[
      "                ",
      "     ooooo      ",
      "   ooooooooo    ",
      "  ooooooooooo   ",
      "  ooooooooooo   ",
      " oooooo oooooo  ",
      " ooooo   ooooo  ",
      " oooo     oooo  ",
      " ooo       ooo  ",
      " oo         oo  ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",
      "                ",]);

    // tiles

    vid.setTileData(0, &[(' ',0)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "        ",
      "        ",
      "        ",
      "        "]);
    vid.setTileData(1, &[(' ',0), ('#',7)], &[
      "        ",
      "        ",
      "        ",
      "   ##   ",
      "   ##   ",
      "        ",
      "        ",
      "        "]);
    vid.setTileData(2, &[(' ',0), ('#',11)], &[
      "  ####  ",
      " ###### ",
      "########",
      "########",
      "########",
      "########",
      " ###### ",
      "  ####  "]);

    vid.setTileData(3, &[(' ',0), ('@',4)], &[
      "    @@@@",
      "  @@    ",
      " @      ",
      " @   @@@",
      "@   @   ",
      "@  @    ",
      "@  @    ",
      "@  @    ",]);
    vid.setTileData(4, &[(' ',0), ('@',4)], &[
      "@@@@    ",
      "    @@  ",
      "      @ ",
      "@@@   @ ",
      "   @   @",
      "    @  @",
      "    @  @",
      "    @  @",]);
    vid.setTileData(5, &[(' ',0), ('@',4)], &[
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@   @   ",
      " @   @@@",
      " @      ",
      "  @@    ",
      "    @@@@",]);
    vid.setTileData(6, &[(' ',0), ('@',4)], &[
      "    @  @",
      "    @  @",
      "    @  @",
      "   @   @",
      "@@@   @ ",
      "      @ ",
      "    @@  ",
      "@@@@    ",]);

    vid.setTileData(7, &[(' ',0), ('@',4)], &[
      "@@@@@@@@",
      "        ",
      "        ",
      "     @@@",
      "    @   ",
      "   @    ",
      "   @    ",
      "   @    "]);
    vid.setTileData(8, &[(' ',0), ('@',4)], &[
      "@@@@@@@@",
      "        ",
      "        ",
      "@@@     ",
      "   @    ",
      "    @   ",
      "    @   ",
      "    @   "]);
    vid.setTileData(9, &[(' ',0), ('@',4)], &[
      "   @    ",
      "   @    ",
      "   @    ",
      "    @   ",
      "     @@@",
      "        ",
      "        ",
      "@@@@@@@@",]);
    vid.setTileData(10, &[(' ',0), ('@',4)], &[
      "    @   ",
      "    @   ",
      "    @   ",
      "   @    ",
      "@@@     ",
      "        ",
      "        ",
      "@@@@@@@@",]);

    vid.setTileData(11, &[(' ',0), ('@',4)], &[
      "@       ",
      "@       ",
      "@       ",
      "@    @@@",
      "@   @   ",
      "@  @    ",
      "@  @    ",
      "@  @    "]);
    vid.setTileData(12, &[(' ',0), ('@',4)], &[
      "       @",
      "       @",
      "       @",
      "@@@    @",
      "   @   @",
      "    @  @",
      "    @  @",
      "    @  @"]);
    vid.setTileData(13, &[(' ',0), ('@',4)], &[
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@   @   ",
      "@    @@@",
      "@       ",
      "@       ",
      "@       ",]);
    vid.setTileData(14, &[(' ',0), ('@',4)], &[
      "    @  @",
      "    @  @",
      "    @  @",
      "   @   @",
      "@@@    @",
      "       @",
      "       @",
      "       @",]);
    vid.setTileData(15, &[(' ',0), ('@',4)], &[
      "@@@@@@@@",
      "        ",
      "        ",
      "@@@@@@@@",
      "        ",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(16, &[(' ',0), ('@',4)], &[
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@  @    ",
      "@  @    ",]);
    vid.setTileData(17, &[(' ',0), ('@',4)], &[
      "    @  @",
      "    @  @",
      "    @  @",
      "    @  @",
      "    @  @",
      "    @  @",
      "    @  @",
      "    @  @",]);
    vid.setTileData(18, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "@@@@@@@@",
      "        ",
      "        ",
      "@@@@@@@@",]);
    vid.setTileData(19, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "      @@",
      "     @  ",
      "    @   ",
      "    @   "]);
    vid.setTileData(20, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "@@      ",
      "  @     ",
      "   @    ",
      "   @    "]);
    vid.setTileData(21, &[(' ',0), ('@',4)], &[
      "    @   ",
      "    @   ",
      "     @  ",
      "      @@",
      "        ",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(22, &[(' ',0), ('@',4)], &[
      "   @    ",
      "   @    ",
      "  @     ",
      "@@      ",
      "        ",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(23, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "     @@@",
      "    @   ",
      "   @    ",
      "   @    ",
      "   @    "]);
    vid.setTileData(24, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "@@@     ",
      "   @    ",
      "    @   ",
      "    @   ",
      "    @   "]);
    vid.setTileData(25, &[(' ',0), ('@',4)], &[
      "   @    ",
      "   @    ",
      "   @    ",
      "    @   ",
      "     @@@",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(26, &[(' ',0), ('@',4)], &[
      "    @   ",
      "    @   ",
      "    @   ",
      "   @    ",
      "@@@     ",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(27, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "@@@@@@@@",
      "        ",
      "        ",
      "        "]);
    vid.setTileData(28, &[(' ',0), ('@',4)], &[
      "    @   ",
      "    @   ",
      "    @   ",
      "    @   ",
      "    @   ",
      "    @   ",
      "    @   ",
      "    @   "]);
    vid.setTileData(29, &[(' ',0), ('@',4)], &[
      "   @    ",
      "   @    ",
      "   @    ",
      "   @    ",
      "   @    ",
      "   @    ",
      "   @    ",
      "   @    "]);
    vid.setTileData(30, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "@@@@@@@@",
      "        ",
      "        ",
      "        ",
      "        "]);
    vid.setTileData(31, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "    @@@@",
      "    @   ",
      "    @   ",
      "    @  @"]);
    vid.setTileData(32, &[(' ',0), ('@',4)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "@@@@    ",
      "   @    ",
      "   @    ",
      "@  @    "]);
    vid.setTileData(33, &[(' ',0), ('@',4)], &[
      "    @  @",
      "    @   ",
      "    @   ",
      "    @@@@",
      "        ",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(34, &[(' ',0), ('@',4)], &[
      "@  @    ",
      "   @    ",
      "   @    ",
      "@@@@    ",
      "        ",
      "        ",
      "        ",
      "        ",]);
    vid.setTileData(35, &[(' ',0), ('-',5)], &[
      "        ",
      "        ",
      "        ",
      "        ",
      "        ",
      "--------",
      "--------",
      "        ",]);

    vid.setFieldData(&[(' ',0), ('.',1), ('*',2),
      // double corners
      ('A',3), ('B',4), ('C',5), ('D',6),
      ('E',7), ('F',8), ('G',9), ('H',10),
      ('I',11),('J',12),('K',13),('L',14),
      // double edges
      ('M',15), ('N',16), ('O',17), ('P',18),
      // single corner narrow
      ('a',19), ('b',20), ('c',21), ('d',22),
      // single corner wide
      ('e',23), ('f',24), ('g',25), ('h',26),
      // single edge
      ('i',27),('j',28),('k',29),('l',30),
      // hard corner
      ('m',31),('n',32),('o',33),('p',34),
      // door
      ('q',35)], &[
      "           N jk O           ",
      "           N jk O           ",
      "           N jk O           ",
      "AMMMMMMMMMMd cd cMMMMMMMMMMB",
      "N............  ............O",
      "N.aiib.aiiib.ab.aiiib.aiib.O",
      "N*j  k.j   k.jk.j   k.j  k*O",
      "N.clld.cllld.cd.cllld.clld.O",
      "N..........................O",
      "N.aiib.ab.aiiiiiib.ab.aiib.O",
      "N.clld.jk.cllfelld.jk.clld.O",
      "N......jk....jk....jk......O",
      "CPPPPb.jgiib jk aiihk.aPPPPD",
      "     N.jelld cd cllfk.O     ",
      "     N.jk          jk.O     ",
      "     N.jk mPPqqPPn jk.O     ",
      "MMMMMd.cd O      N cd.cMMMMM",
      "      .   O      N   .      ",
      "PPPPPb.ab O      N ab.aPPPPP",
      "     N.jk oMMMMMMp jk.O     ",
      "     N.jk          jk.O     ",
      "     N.jk aiiiiiib jk.O     ",
      "AMMMMd.cd cllfelld cd.cMMMMB",
      "N............jk............O",
      "N.aiib.aiiib.jk.aiiib.aiib.O",
      "N.clfk.cllld.cd.cllld.jeld.O",
      "N*..jk.......  .......jk..*O",
      "Kib.jk.ab.aiiiiiib.ab.jk.aiL",
      "Ild.cd.jk.cllfelld.jk.cd.clJ",
      "N......jk....jk....jk......O",
      "N.aiiiihgiib.jk.aiihgiiiib.O",
      "N.clllllllld.cd.clllllllld.O",
      "N..........................O",
      "CPPPPPPPPPPb ab aPPPPPPPPPPD",
      "           N jk O           ",
      "           N jk O           ",]);
}
